config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  root to: 'dashboard/pages#start'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, path_names: { sign_in: 'connexion', sign_up: "inscription" }
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }, path_names: { sign_in: 'connexion', sign_up: "inscription" }

  get "scrapper", to: "pages#scrapper", as: "scrapper"
  get "user_to_csv", to: "pages#generate_users_csv_infos", as: "user_csv"

  namespace :widgets do
    get ':template', to: 'pages#simulation', as: "simulation"
  end

  namespace :dashboard do
    get "start", to: "pages#start", as: "start"
    get "synthesis", to: "pages#synthesis", as: "synthesis"
    get "restricted_synthesis", to: "pages#restricted_synthesis", as: "restricted_synthesis"
    get "management", to: "pages#management", as: "management"
    get "sells", to: "pages#sells", as: "sells"
    get "costs", to: "pages#costs", as: "costs"
    get "treasury", to: "pages#treasury", as: "treasury"
    resources :companies
    resources :compromises
    resources :costs
    resources :subscriptions
    resources :subscription_types
    resources :subscription_items
    resources :users, only: [:edit, :update]
    resources :user_questions, only: [:new, :create]
    resources :financing_requests, only: [:new, :create]
    get "subscriptions/dynamic_field/:field", to: "subscriptions#dynamic_field", as: "dynamic_field"
    get "subscriptions/close/:id", to: "subscriptions#close", as: "subscription_close"
    get "subscriptions/renew/:id", to: "subscriptions#renew", as: "subscription_renew"

    get "financing_request_success", to: "financing_requests#success", as: "financing_request_success"
    get "new_pending", to: "compromises#new_pending", as: "new_pending"
    get "compromises/validation/:id", to: "compromises#validation", as: "validation"
    post "compromises/signed/:id", to: "compromises#signed", as: "compromise_signed"
    post "compromises/change_signed_date/:id", to: "compromises#change_signed_date", as: "compromise_change_signed_date"
    post "compromises/update_act_signature_date/:id", to: "compromises#update_act_signature_date", as: "compromise_update_act_signature_date"

    post "month-costs", to: "costs#month_costs", as: "month_costs"
    post "year-costs", to: "costs#year_costs", as: "year_costs"
    get "polls/sad", to: "polls#sad"
    get "polls/mitigate", to: "polls#mitigate"
    get "polls/happy", to: "polls#happy"

    get "account/subscription", to: "users#infos", as: "subscription_infos"
    get "account/subscription/success", to: "users#subscription_success", as: "subscription_success"
    post "account/subscription/cancel", to: "users#stripe_subscription_cancel", as: "subscription_cancel"
    post "acccount/subscription/coupon", to: "users#coupon_code", as: "coupon_code"

  end

  namespace :admin do
    resources :users
    resources :user_scorings
    resources :companies
    resources :compromises
    resources :compromise_scorings
    resources :financing_requests
    resources :admins
    get "start",  to: "pages#start", as: "start"
    get "test_api_call", to: "payments#test_api_call", as: "test_payment"
    post "payment_data", to: "payments#payment_data", as: "payment_data"
    get "payments/success", to: "payments#success", as: "payment_success"
    namespace :webhooks do
      namespace :payments do
        post "checkout/completed", to: "checkouts#completed", as: "checkout_completed"
        post "subscription/trial_will_end", to: "subscriptions#trial_will_end", as: "subscription_trial_will_end"
        post "subscription/updated", to: "subscriptions#updated", as: "subscription_updated"
        post "subscription/deleted", to: "subscriptions#deleted", as: "subscription_deleted"
        post "customer/updated", to: "customers#updated", as: "customer_updated"
      end
    end
  end

  namespace :wizard do
    resources :users
    get "success", to: "users#success", as: "success"
  end

  get "/404", to: "errors#not_found", as: "notfound"
  get "/500", to: "errors#internal_error", as: "internal_error"
  get '*unmatched_route', to: 'application#not_found_redirect'

end

app/controllers/dashboard/companies_controller.rb
class Dashboard::CompaniesController < ApplicationController

  def show
  end

  def index
    @companies = current_user.companies
    @company = current_user.companies.last
    @current_page = dashboard_companies_path

    if request.xhr?
      render :index, layout: false
    else
      render :index, layout: "ajax"
    end
  end

  def edit
    puts "---- PARAMS ----"
    puts params.inspect
    puts "----------------"
    @company = Company.find(params[:id])
    render :edit, layout: false
  end

  def update
    puts "---- PARAMS COMPANY UPDATE ----"
    puts params.inspect
    puts "----------------"
    @company = Company.find(params[:id])
    if @company.update(safe_params)
      @current_page = dashboard_companies_path
      render :index, layout: false
    else
      render :edit, layout: false
    end
  end

  def new
  end

  def destroy
  end

  private

  def safe_params
    params.require(:company).permit(:company_status, :kbis, :official_attestation, :name, :legal_name, :trade_name, :siret, :siren, :company_type, :localisation)
  end

end

app/controllers/dashboard/compromises_controller.rb
class Dashboard::CompromisesController < ApplicationController
  before_action :authenticate_user!, except: [:validation]
  skip_before_action :verify_authenticity_token, only: [:signed,:change_signed_date]

  def show
    @compromise = Compromise.find(params[:id])
    @referer = dashboard_compromises_path
    @user_question = UserQuestion.new
    @referer_title = "Retour au tableau des compromis"
    if request.xhr?
      render :show, layout: false
    else
      render :show, layout: "ajax"
    end
  end

  def index
    @companies = current_user.companies
    @company = current_user.companies.last
    @compromises = @companies.to_a.map{|company| company.compromises}.flatten

    @resource_name = "#{controller_name}-#{action_name}"
    # flash.now[:info] = {title: "Info", content: "Retrouvez ici tous vos compromis", template: "info", date: l(Time.now, format: :time_without_seconds)}

    if current_user.has_platform_access?
      if request.xhr?
        render :index, layout: false
      else
        render :index, layout: "ajax"
      end
    else
      @restricted_access = true
      if request.xhr?
        render :index, layout: false
      else
        render :index, layout: "ajax"
      end
    end
  end

  def new
    @company = current_user.companies.last
    @compromise = @company.compromises.build
    if request.xhr?
      render :new, layout: false
    else
      render :new, layout: "ajax"
    end
  end

  def edit
    @compromise = Compromise.find(params[:id])
    render :edit, layout: false
  end

  def update
    @compromise = Compromise.find(params[:id])
    if @compromise.update(safe_params)
      @user_question = UserQuestion.new
      render :show, layout: false
    else
      puts @compromise.errors_full_messages
      render :edit, layout: false
    end
  end

  def new_pending
    @company = current_user.companies.last
    @compromise = @company.compromises.build
    render :new_pending, layout: false
  end

  def validation
    puts params
    puts params[:id]
    @compromise = Compromise.find(params[:id])
    @user = @compromise.company.user

    if @user
      sign_in @user
    end

    puts @compromise
    render :validation
  end

  def signed
    @compromise = Compromise.find(params[:id])
    @compromise[:status] = 0
    if @compromise.save
      render :validation_success, layout: false
    else
      puts @compromise.errors.full_messages
      render :validation_fail, layout: false
    end
  end

  def change_signed_date
    @compromise = Compromise.find(params[:id])
    render :change_signed_date, layout: false
  end

  def update_act_signature_date
    @compromise = Compromise.find(params[:id])
    if @compromise.update(safe_params)
      render :validation_success, layout: false
    else
      render :change_signed_date, layout: false
    end
  end

  def create
    @compromise = Compromise.new(safe_params)
    if @compromise.save
      @company = current_user.companies.last
      @compromises = current_user.companies.last.compromises
      @resource_name = "compromises-index"

      current_user.points += 150
      current_user.save
      # flash.now[:create] = {title: "Compromis crée", instance: @compromise, template: "create", date: l(Time.now, format: :time_without_seconds)}
      render :index, layout: false
    else
      puts  @compromise.errors.full_messages
      if params[:compromise][:pending_compromise]
        render :new, layout: false
      else
        render :new_pending, layout: false
      end
    end
  end

  private

  def safe_params
    params.require(:compromise).permit(:pending_compromise,:authentic_act_signature_date,:compromise_signature_place,:selling_price,:pending_funding_terms,:contract_type,:compromise_signature_date,:seller_lastname,:status,:reference,:fees,:purchase_type,:company_id)
  end

end

app/controllers/dashboard/costs_controller.rb
class Dashboard::CostsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:month_costs, :year_costs]

  def new
    @company = current_user.companies.last
    if @company.cost_reference
      puts @company.cost_reference
    else
      puts "There is no cost reference for this company !!!!"
    end
    @cost = Cost.new
    render :new, layout: false
  end

  def create
    @cost = Cost.new(safe_params)
    @company = current_user.companies.last
    @month = params[:cost][:month].to_i
    @year = params[:cost][:year].to_i

    @date = Date.parse("#{@year}/#{@month}")
    current_month_subs_sum = @company.subscriptions.where(:start_date.lte => @date, :end_date.gt => @date).map{|sub| sub.int_amount}.sum

    if @cost.save
      @costs = @company.costs
      @datas = [@cost.rent.to_i,@cost.wages.to_i,@cost.subscriptions.to_i,@cost.others.to_i]
      @datas[2] = current_month_subs_sum ? current_month_subs_sum : 0
      @costs_total = @datas.sum
      render partial: "dashboard/costs/partials/show", locals: {cost: @cost, month: @month, datas: @datas, costs_total: @costs_total}
    else
      puts @cost.errors.full_messages
      render :new, layout: false
    end
  end

  def edit
    @cost = Cost.find(params[:id])
    @company = @cost.company
    @month = @cost.month.to_i
    @year = @cost.year.to_i

    @datas = [@cost.rent.to_i,@cost.wages.to_i,@cost.subscriptions.to_i,@cost.others.to_i]

    @date = Date.parse("#{@year}/#{@month}")
    current_month_subs_sum = @company.subscriptions.where(:start_date.lte => @date, :end_date.gt => @date).map{|sub| sub.int_amount}.sum

    @datas[2] = current_month_subs_sum ? current_month_subs_sum : 0
    @costs_total = @datas.sum

    render :edit, layout: false
  end

  def update
    @cost = Cost.find(params[:id])
    @company = @cost.company
    if @cost.update(safe_params)
      render partial: "dashboard/costs/partials/show", locals: {cost: @cost, month: @cost.month, datas: @cost.datas, costs_total: @cost.total, company: @company}
    else
      render :edit, layout: false
    end
  end

  def show
    @cost = Cost.find(params[:id])
    render :show
  end

  def month_costs
    @company = current_user.companies.last
    @month = params["month"].to_i
    @year = params["year"].to_i
    @cost = current_user.companies.last.costs.find_by(month: @month, year: @year)

    @date = Date.parse("#{@year}/#{@month}")
    current_month_subs_sum = @company.subscriptions.where(:start_date.lte => @date, :end_date.gt => @date).map{|sub| sub.int_amount}.sum

    if @cost
      @datas = [@cost.rent.to_i,@cost.wages.to_i,@cost.subscriptions.to_i,@cost.others.to_i]
      @month_subs_sum = @company.subscriptions_amount_sum
      @datas[2] = current_month_subs_sum ? current_month_subs_sum : 0
      @costs_total = @datas.sum
      render partial: "dashboard/costs/partials/show", locals: {cost: @cost, month: @month, datas: @datas, costs_total: @costs_total}
    else
      @datas = [0,0,current_month_subs_sum,0]
      @cost = Cost.new
      render :new, layout: false
    end
  end

  def year_costs
    @year = params[:year]
    @month = 1
    @company = current_user.companies.last
    @cost = @company.costs.find_by(month: 1,year: @year)

    if @company.cost_reference
      puts @company.cost_reference
    else
      puts "There is no cost reference for this company !!!!"
    end

    if @cost
      @costs = current_user.companies.last.costs
      @datas = [@cost.rent.to_i,@cost.wages.to_i,@cost.subscriptions.to_i,@cost.others.to_i]
      @sub_total = @company.subscriptions_amount_sum
      @datas[2] = @sub_total ? @sub_total : 0
      @costs_total = @datas.sum
    else
      @company = current_user.companies.last
      @month = 1
      @new_cost = Cost.new
    end
    render partial: "dashboard/pages/partials/management/costs"
  end

  private

  def safe_params
    params.require(:cost).permit(:month, :year, :rent, :subscriptions, :wages, :others, :company_id)
  end

end

app/controllers/dashboard/financing_requests_controller.rb
class Dashboard::FinancingRequestsController < ApplicationController

  def new
    @user = current_user
    @company = @user.companies.last
    @financing_request = FinancingRequest.new
    if request.xhr?
      render :new, layout: false
    else
      render :new, layout: "ajax"
    end
  end

  def create
    @financing_request = FinancingRequest.new(safe_params)
    if @financing_request.save
      puts "---- FinancingRequest object ----"
      puts @financing_request.inspect
      @user = @financing_request.company.user

      ["philippe@bientotchezsoi.com","annegaelle@bientotchezsoi.com","aurelien@bientotchezsoi.com"].each do |email|
        UserMailer.admin_financing_request(@user,@user.companies.last,@financing_request,email).deliver
      end

      UserMailer.financing_request(@user).deliver
      render :success, layout: false
    else
      puts @financing_request.errors.full_messages
      @user = current_user
      @company = @user.companies.last
      render :new, layout: false
    end
  end

  def success
    render :success, layout: false
  end

  private

  def safe_params
    params.require(:financing_request).permit(:company_id,:year_transactions_count,:pending_transactions_count,:annual_revenue,:total_transactions_amount,:company_creation_year)
  end

end

app/controllers/dashboard/polls_controller.rb
class Dashboard::PollsController < ApplicationController

  def sad
    @user = User.find(params[:id])
    @poll = Poll.find(params[:poll_id])
    @user.polls.push(@poll)
    @poll.negative += 1
    @poll.save
    render partial: "dashboard/polls/partials/seen", locals: {poll: @poll}
  end

  def mitigate
    @user = User.find(params[:id])
    @poll = Poll.find(params[:poll_id])
    @user.polls.push(@poll)
    @poll.mitigate += 1
    @poll.save
    render partial: "dashboard/polls/partials/seen", locals: {poll: @poll}
  end

  def happy
    @user = User.find(params[:id])
    @poll = Poll.find(params[:poll_id])
    @user.polls.push(@poll)
    @poll.positive += 1
    @poll.save
    render partial: "dashboard/polls/partials/seen", locals: {poll: @poll}
  end

end

app/controllers/dashboard/subscription_items_controller.rb
class Dashboard::SubscriptionItemsController < ApplicationController

  def show
    @company = current_user.companies.last
    @subscription = Subscription.new
    @sub_item = SubscriptionItem.find(params[:id])
    render :show, layout: false
  end

  def edit
    @company = current_user.companies.last
    @sub_item = SubscriptionItem.find(params[:id])
    @sub_type = @sub_item.subscription_type

    puts "---- Subs by category ----"
    puts @company.subscriptions_by_category
    puts "--------------------------"

    @result = SubscriptionItem.slug_names & @company.subscriptions_names

    @subscription = @company.subscriptions.find_by(slug_name: @sub_item.slug_name)
    render :edit, layout: false
  end

end

app/controllers/dashboard/subscription_types_controller.rb
class Dashboard::SubscriptionTypesController < ApplicationController

  def show
    @company = current_user.companies.last
    @sub = SubscriptionType.find(params[:id])
    @subs_items = @sub.subscription_items
    render :show, layout: false
  end

end

app/controllers/dashboard/user_questions_controller.rb
class Dashboard::UserQuestionsController < ApplicationController

  def new
    @user_question = UserQuestion.new
    render partial: "dashboard/user_questions/partials/new", locals: {user_question: @user_question}
  end

  def create
    @user_question = UserQuestion.new(safe_params)
    if @user_question.save
      @user = User.find(@user_question.user_id)
      @company = @user.companies.last

      ["philippe@bientotchezsoi.com","annegaelle@bientotchezsoi.com","aurelien@bientotchezsoi.com"].each do |email|
        UserMailer.user_question(@user,@user_question,@company,email).deliver
      end

      render "dashboard/user_questions/success", layout: false
    else
      render partial: "dashboard/user_questions/partials/new", locals: {user_question: @user_question}
    end
  end

  private

  def safe_params
    params.require(:user_question).permit(:user_id, :object, :message)
  end

end

app/views/dashboard/shared/_account_menu.html.haml
%section.account-menu
  .d-flex.ai-start.d-column
    %h3
      = title
    - if @referer
      .d-flex.justify-content-start
        = remote_link_to(target: @referer, class: "referer-link", dynamic_dom_receiver: "section.content", trackable_url: true) do
          = feather_svg("arrow-left")
          .referer-title
            = @referer_title

  .dropdown.d-none
    .account-menu-container{"aria-expanded": "false", "aria-haspopup": "true", "data-toggle": "dropdown"}
      .feather-svg-lightred
        = feather_svg("unicon-user-circle")
      .agent-mail
        = "#{current_user.firstname.downcase.capitalize} #{current_user.lastname.downcase.capitalize}"
      .feather-svg-darkblue
        = feather_svg("chevron-down")
    .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenuButton"}
      = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", pattern: "html", trackable_url: true) do
        .dropdown-item
          .feather-svg-lightred.mr-2
            = feather_svg("settings")
          Profil et paramètres
      = link_to destroy_user_session_path, method: :delete do
        .dropdown-item
          .feather-svg-lightred.mr-2
            = feather_svg("log-out")
          Déconnexion

app/views/dashboard/shared/_backlink.html.haml
- if @referer
  .d-flex.justify-content-start
    = remote_link_to(target: @referer, class: "referer-link", dynamic_dom_receiver: "section.content", trackable_url: true) do
      = feather_svg("arrow-left")
      .referer-title
        = @referer_title

app/views/dashboard/shared/_current_path.html.haml
= ajax_current_url(url: request.referer)

app/views/dashboard/shared/_fixed_menu.html.haml
%section.fixed-menu.mobile-hidden
  .fadein
    .logo
      = svg("logo-edmond")
    = remote_link_to(target: dashboard_synthesis_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item.active
        = feather_svg("home")
        %h5 Dashboard
    = remote_link_to(target: dashboard_management_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "tachometer-fast", size: 25, color: "white")
        %h5 Pilotage
    = remote_link_to(target: dashboard_compromises_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = feather_svg("flag")
        %h5 Mes transactions
    = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "user-circle", size: 25, color: "white")
        %h5 Ma société
    = remote_link_to(target: dashboard_subscription_infos_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true, class: "useless") do
      .menu-item
        = unicon_svg(name: "store-alt", size: 25, color: "white")
        %h5 Mon abonnement

%section.mobile-menu-trigger.d-md-none
  .round-svg.mobile-btn-trigger
    = feather_svg("align-justify")
%section.mobile-menu-content.d-none
  .mobile-menu-closer
    = feather_svg("x")

  .pt-5
    = remote_link_to(target: dashboard_synthesis_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item.active
        = feather_svg("home")
        %h5 Dashboard
    = remote_link_to(target: dashboard_management_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "tachometer-fast", size: 25, color: "white")
        %h5 Pilotage
    = remote_link_to(target: dashboard_compromises_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = feather_svg("flag")
        %h5 Mes transactions
    = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "store-alt", size: 25, color: "white")
        %h5 Ma société

app/views/dashboard/shared/_fixed_menu_with_request_datas.html.haml
%section.fixed-menu.mobile-hidden
  .fadein
    .logo
      = svg("logo-edmond")
    = remote_link_to(target: dashboard_synthesis_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item{class: "#{'active' if current_page?(dashboard_synthesis_path)}"}
        = feather_svg("home")
        %h5 Dashboard
    = remote_link_to(target: dashboard_management_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item{class: "#{'active' if request.original_url.match? /management|treasury|sells|costs|subscriptions|financing_requests/}"}
        = unicon_svg(name: "tachometer-fast", size: 25, color: "white")
        %h5 Pilotage
    = remote_link_to(target: dashboard_compromises_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item{class: "#{'active' if request.original_url.include?('compromises')}"}
        = feather_svg("flag")
        %h5 Mes transactions
    = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item{class: "#{'active' if current_page?(dashboard_companies_path)}"}
        = unicon_svg(name: "user-circle", size: 25, color: "white")
        %h5 Ma société
    = remote_link_to(target: dashboard_subscription_infos_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true, class: "useless") do
      .menu-item{class: "#{'active' if current_page?(dashboard_subscription_infos_path)}"}
        = unicon_svg(name: "store-alt", size: 25, color: "white")
        %h5 Mon abonnement

%section.mobile-menu-trigger.d-md-none
  .round-svg.mobile-btn-trigger
    = feather_svg("align-justify")
%section.mobile-menu-content.d-none
  .mobile-menu-closer
    = feather_svg("x")

  .pt-5
    = remote_link_to(target: dashboard_synthesis_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item.active
        = feather_svg("home")
        %h5 Dashboard
    = remote_link_to(target: dashboard_management_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "tachometer-fast", size: 25, color: "white")
        %h5 Pilotage
    = remote_link_to(target: dashboard_compromises_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = feather_svg("flag")
        %h5 Mes transactions
    = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", toggable: ".menu-item", trackable_url: true) do
      .menu-item
        = unicon_svg(name: "store-alt", size: 25, color: "white")
        %h5 Ma société

app/views/dashboard/shared/_fixed_user_menu.html.haml
%section.fixed_user_menu.mobile-hidden
  .d-flex.mr-3
    = remote_link_to(target: dashboard_companies_path, dynamic_dom_receiver: "section.content", pattern: "html", class: "fixed-menu-link", trackable_url: true) do
      .feather-svg-lightred.mr-2
        = feather_svg("user")
      Profil et paramètres
  .d-flex
    = link_to destroy_user_session_path, method: :delete, class: "fixed-menu-link" do
      .feather-svg-lightred.mr-2
        = feather_svg("log-out")
      Déconnexion